msgid ""
msgstr ""
"Project-Id-Version: 98e6872775a91bf27122ff608b6db605\n"
"Report-Msgid-Bugs-To: https://gitlab.gnome.org/GNOME/glib-networking/issues\n"
"POT-Creation-Date: 2019-07-04 09:53+0000\n"
"PO-Revision-Date: 2020-06-04 11:51\n"
"Last-Translator: Zander Brown <zbrown@gnome.org>\n"
"Language-Team: Belarusian\n"
"Language: be_BY\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=4; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : n%10==0 || n%10>=5 && n%10<=9 || n%100>=11 && n%100<=14 ? 2 : 3);\n"
"X-Generator: Gtranslator 3.32.1\n"
"X-Crowdin-Project: 98e6872775a91bf27122ff608b6db605\n"
"X-Crowdin-Language: be\n"
"X-Crowdin-File: /master/sources/glib-networking/en_GB.po\n"

#: proxy/libproxy/glibproxyresolver.c:159
msgid "Proxy resolver internal error."
msgstr "Унутраная памылка распазнавальніка проксі."

#: tls/base/gtlsconnection-base.c:479 tls/base/gtlsinputstream.c:78
#: tls/base/gtlsinputstream.c:141 tls/base/gtlsoutputstream.c:78
#: tls/base/gtlsoutputstream.c:143
msgid "Connection is closed"
msgstr "Злучэнне закрыта"

#. Cannot perform a blocking operation during a handshake on the
#. * same thread that triggered the handshake. The only way this can
#. * occur is if the application is doing something weird in its
#. * accept-certificate callback. Allowing a blocking op would stall
#. * the handshake (forever, if there's no timeout). Even a close
#. * op would deadlock here.
#.
#: tls/base/gtlsconnection-base.c:549
msgid "Cannot perform blocking operation during TLS handshake"
msgstr "Немагчыма выканаць аперацыю блакавання падчас вітання TLS"

#: tls/base/gtlsconnection-base.c:612 tls/base/gtlsconnection-base.c:1118
msgid "Socket I/O timed out"
msgstr "Тэрмін чакання уводу/вываду з сокета сыйшоў"

#: tls/base/gtlsconnection-base.c:1339
msgid "Peer does not support safe renegotiation"
msgstr "Пір не падтрымлівае бяспечнае пераўзгадненне"

#: tls/base/gtlsconnection-base.c:1382
msgid "Server required TLS certificate"
msgstr "Сервер запатрабаваў сертыфікат TLS"

#: tls/base/gtlsconnection-base.c:1477 tls/gnutls/gtlsconnection-gnutls.c:419
#: tls/openssl/gtlsconnection-openssl.c:172
#, c-format
msgid "Unacceptable TLS certificate"
msgstr "Непрыдатны сертыфікат TLS"

#: tls/base/gtlsconnection-base.c:1884
#, c-format
msgid "Receive flags are not supported"
msgstr "Атрыманыя сцягі не падтрымліваюцца"

#: tls/base/gtlsconnection-base.c:2019
#, c-format
msgid "Send flags are not supported"
msgstr "Сцягі не падтрымліваюцца"

#: tls/gnutls/gtlscertificate-gnutls.c:178
#: tls/openssl/gtlscertificate-openssl.c:170
#, c-format
msgid "Could not parse DER certificate: %s"
msgstr "Не атрымалася разабраць сертыфікат DER: %s"

#: tls/gnutls/gtlscertificate-gnutls.c:199
#: tls/openssl/gtlscertificate-openssl.c:190
#, c-format
msgid "Could not parse PEM certificate: %s"
msgstr "Не атрымалася разабраць сертыфікат PEM: %s"

#: tls/gnutls/gtlscertificate-gnutls.c:230
#: tls/openssl/gtlscertificate-openssl.c:209
#, c-format
msgid "Could not parse DER private key: %s"
msgstr "Не атрымалася разабраць асабісты ключ DER: %s"

#: tls/gnutls/gtlscertificate-gnutls.c:261
#: tls/openssl/gtlscertificate-openssl.c:228
#, c-format
msgid "Could not parse PEM private key: %s"
msgstr "Не атрымалася разабраць асабісты ключ PEM: %s"

#: tls/gnutls/gtlscertificate-gnutls.c:297
#: tls/openssl/gtlscertificate-openssl.c:263
msgid "No certificate data provided"
msgstr "Даныя сертыфіката не пададзеныя"

#: tls/gnutls/gtlsconnection-gnutls.c:224
#: tls/openssl/gtlsclientconnection-openssl.c:522
#: tls/openssl/gtlsserverconnection-openssl.c:399
#, c-format
msgid "Could not create TLS connection: %s"
msgstr "Не атрымалася стварыць злучэнне TLS: %s"

#: tls/gnutls/gtlsconnection-gnutls.c:353
#: tls/gnutls/gtlsconnection-gnutls.c:364
#: tls/gnutls/gtlsconnection-gnutls.c:388
#: tls/openssl/gtlsconnection-openssl.c:139
#, c-format
#| msgid "Peer failed to perform TLS handshake"
msgid "Peer failed to perform TLS handshake: %s"
msgstr "У піра не атрымалася выканаць вітанне TLS: %s"

#: tls/gnutls/gtlsconnection-gnutls.c:375
#: tls/openssl/gtlsconnection-openssl.c:248
msgid "Peer requested illegal TLS rehandshake"
msgstr "Пір запытаў недапушчальнае паўторнае вітанне TLS"

#: tls/gnutls/gtlsconnection-gnutls.c:396
msgid "TLS connection closed unexpectedly"
msgstr "Злучэнне TLS нечакана закрылася"

#: tls/gnutls/gtlsconnection-gnutls.c:411
#: tls/openssl/gtlsconnection-openssl.c:164
msgid "TLS connection peer did not send a certificate"
msgstr "Пір, з якім наладжваецца злучэнне TLS, не адправіў сертыфікат"

#: tls/gnutls/gtlsconnection-gnutls.c:427
#, c-format
msgid "Peer sent fatal TLS alert: %s"
msgstr "Пір адправіў фатальнае апавяшчэнне TLS: %s"

#: tls/gnutls/gtlsconnection-gnutls.c:437
msgid "Protocol version downgrade attack detected"
msgstr "Выяўлена атака на аснове паніжэння версіі пратаколу"

#: tls/gnutls/gtlsconnection-gnutls.c:446
#, c-format
msgid "Message is too large for DTLS connection; maximum is %u byte"
msgid_plural "Message is too large for DTLS connection; maximum is %u bytes"
msgstr[0] "Паведамленне задоўгае для злучэння DTLS; дапускаецца не больш за %u байт"
msgstr[1] "Паведамленне задоўгае для злучэння DTLS; дапускаецца не больш за %u байты"
msgstr[2] "Паведамленне задоўгае для злучэння DTLS; дапускаецца не больш за %u байтаў"
msgstr[3] "Паведамленне задоўгае для злучэння DTLS; дапускаецца не больш за %u байтаў"

#: tls/gnutls/gtlsconnection-gnutls.c:455
msgid "The operation timed out"
msgstr "Тэрмін чакання аперацыі сыйшоў"

#: tls/gnutls/gtlsconnection-gnutls.c:780
#, c-format
msgid "Error performing TLS handshake: %s"
msgstr "Падчас выканання вітання TLS адбылася памылка: %s"

#: tls/gnutls/gtlsconnection-gnutls.c:883
#: tls/openssl/gtlsconnection-openssl.c:257
#: tls/openssl/gtlsconnection-openssl.c:307
#| msgid "Error performing TLS handshake: %s"
msgid "Error performing TLS handshake"
msgstr "Падчас выканання вітання TLS адбылася памылка"

#: tls/gnutls/gtlsconnection-gnutls.c:929
#: tls/gnutls/gtlsconnection-gnutls.c:989
#: tls/openssl/gtlsconnection-openssl.c:414
#| msgid "Error reading data from TLS socket: %s"
msgid "Error reading data from TLS socket"
msgstr "Падчас чытання даных з сокета TLS адбылася памылка"

#. flags
#: tls/gnutls/gtlsconnection-gnutls.c:1011
#: tls/gnutls/gtlsconnection-gnutls.c:1075
#: tls/openssl/gtlsconnection-openssl.c:458
#| msgid "Error writing data to TLS socket: %s"
msgid "Error writing data to TLS socket"
msgstr "Падчас запісу даных у сокет TLS адбылася памылка"

#: tls/gnutls/gtlsconnection-gnutls.c:1045
#, c-format
msgid "Message of size %lu byte is too large for DTLS connection"
msgid_plural "Message of size %lu bytes is too large for DTLS connection"
msgstr[0] "Паведамленне памеру %lu байт задоўгае для злучэння DTLS"
msgstr[1] "Паведамленне памеру %lu байты задоўгае для злучэння DTLS"
msgstr[2] "Паведамленне памеру %lu байтаў задоўгае для злучэння DTLS"
msgstr[3] "Паведамленне памеру %lu байтаў задоўгае для злучэння DTLS"

#: tls/gnutls/gtlsconnection-gnutls.c:1047
#, c-format
msgid "(maximum is %u byte)"
msgid_plural "(maximum is %u bytes)"
msgstr[0] "(максімум %u байт)"
msgstr[1] "(максімум %u байты)"
msgstr[2] "(максімум %u байтаў)"
msgstr[3] "(максімум %u байтаў)"

#: tls/gnutls/gtlsconnection-gnutls.c:1094
#, c-format
msgid "Error performing TLS close: %s"
msgstr "Падчас закрыцця злучэння TLS адбылася памылка: %s"

#: tls/gnutls/gtlsdatabase-gnutls.c:553
msgid "Failed to load system trust store: GnuTLS was not configured with a system trust"
msgstr "Не атрымалася загрузіць сховішча сістэмнага даверу: GnuTLS наладжаны без сістэмнага даверанага сховішча"

#: tls/gnutls/gtlsdatabase-gnutls.c:558 tls/openssl/gtlsdatabase-openssl.c:187
#, c-format
msgid "Failed to load system trust store: %s"
msgstr "Не атрымалася загрузіць сховішча сістэмнага даверу: %s"

#: tls/gnutls/gtlsserverconnection-gnutls.c:137
#: tls/openssl/gtlsserverconnection-openssl.c:90
msgid "Certificate has no private key"
msgstr "Сертыфікат не мае асабістага ключа"

#: tls/openssl/gtlsclientconnection-openssl.c:412
#: tls/openssl/gtlsclientconnection-openssl.c:469
#: tls/openssl/gtlsserverconnection-openssl.c:288
#: tls/openssl/gtlsserverconnection-openssl.c:339
#, c-format
#| msgid "Could not create TLS connection: %s"
msgid "Could not create TLS context: %s"
msgstr "Не атрымалася стварыць кантэкст TLS: %s"

#: tls/openssl/gtlsconnection-openssl.c:180
#, c-format
#| msgid "Unacceptable TLS certificate"
msgid "Unacceptable TLS certificate authority"
msgstr "Непрыдатны сертыфікат паўнамоцтваў TLS"

#: tls/openssl/gtlsconnection-openssl.c:188
msgid "Digest too big for RSA key"
msgstr "Занадта вялікі дайджэст для ключа RSA"

#: tls/openssl/gtlsconnection-openssl.c:495
#| msgid "Error performing TLS close: %s"
msgid "Error performing TLS close"
msgstr "Падчас закрыцця злучэння TLS адбылася памылка"

#: tls/openssl/gtlsdatabase-openssl.c:227
#| msgid "Could not create TLS connection: %s"
msgid "Could not create CA store"
msgstr "Не атрымалася стварыць сховішча сертыфікатаў"

#: tls/openssl/gtlsfiledatabase-openssl.c:454
#, c-format
msgid "Failed to load file path: %s"
msgstr "Не атрымалася загрузіць шлях да файла: %s"

#: tls/openssl/gtlsserverconnection-openssl.c:101
#, c-format
msgid "There is a problem with the certificate: %s"
msgstr "Узнікла праблема з сертыфікатам: %s"

#: tls/openssl/gtlsserverconnection-openssl.c:109
#, c-format
msgid "There is a problem with the certificate private key: %s"
msgstr "Узнікла праблема з асабістым ключом сертыфіката: %s"

#~ msgid "Operation would block"
#~ msgstr "Operation would block"

#~ msgid "Server did not return a valid TLS certificate"
#~ msgstr "Server did not return a valid TLS certificate"

#~ msgid ""
#~ "This is the last chance to enter the PIN correctly before the token is "
#~ "locked."
#~ msgstr ""
#~ "This is the last chance to enter the PIN correctly before the token is "
#~ "locked."

#~ msgid ""
#~ "Several PIN attempts have been incorrect, and the token will be locked "
#~ "after further failures."
#~ msgstr ""
#~ "Several PIN attempts have been incorrect, and the token will be locked "
#~ "after further failures."

#~ msgid "The PIN entered is incorrect."
#~ msgstr "The PIN entered is incorrect."

#~ msgid "Module"
#~ msgstr "Module"

#~ msgid "PKCS#11 Module Pointer"
#~ msgstr "PKCS#11 Module Pointer"

#~ msgid "Slot ID"
#~ msgstr "Slot ID"

#~ msgid "PKCS#11 Slot Identifier"
#~ msgstr "PKCS#11 Slot Identifier"

#~ msgid "Connection is already closed"
#~ msgstr "Connection is already closed"

